String resumen1 =
    'Es una serie de cómics de superhéroes y una exitosa adaptación animada de Amazon Prime Video, creada por el escritor Robert Kirkman (el mismo creador de The Walking Dead) junto a los artistas Cory Walker y Ryan Ottley. A simple vista parece la clásica historia de superhéroes, pero destaca por su realismo crudo, su violencia explícita y un desarrollo de personajes profundamente humano.';

String dequetrata =
    'La historia sigue a Mark Grayson, un adolescente aparentemente común cuyo padre es Omni-Man (Nolan Grayson), el superhéroe más poderoso del planeta (una especie de Superman alienígena). Al cumplir los 17 años, Mark finalmente hereda los poderes de su padre y adopta la identidad de Invincible.Sin embargo, justo cuando empieza a aprender a ser un héroe bajo la tutela de su padre, Mark descubre un oscuro y terrible secreto sobre el origen de Omni-Man y sus verdaderas intenciones para la Tierra, lo que cambia su vida y el destino del mundo para siempre.';

String pilaresclavedelaserie =
    'Madurez y Realismo Crudo: A diferencia de los cómics tradicionales donde los héroes rara vez sufren daños permanentes, en Invincible las batallas tienen consecuencias reales. Hay muchísima sangre, fracturas, traumas psicológicos y muertes de personajes importantes.Deconstrucción del Género: Juega con los tropos clásicos de DC y Marvel (de hecho, hay parodias evidentes de la Liga de la Justicia), pero les da un giro mucho más realista, político y oscuro.Evolución de Personajes: Mark no es un héroe perfecto; comete errores, fracasa, sufre y madura a golpes (literal y figuradamente). Las relaciones familiares y amorosas tienen un peso enorme en la trama.';

String conquet =
    'Conquest fue un antagonista importante en Invincible , haciendo su debut entre la temporada 3 y la 4 .Como una de las figuras más poderosas del Imperio Viltrum , Conquest era un guerrero veterano de alto rango. Dedicado casi exclusivamente a su misión de dominación universal, servía como la "opción nuclear" fundamental de los Viltrumitas, desplegada solo cuando se consideraba necesaria la máxima fuerza y ​​la absoluta crueldad. Siguiendo instrucciones, Conquest emprendió una misión para determinar si Invincible había cumplido con su deber en la Tierra . Sin embargo, finalmente fue derrotado por él y encarcelado por la Agencia de Defensa Global . Tras su recuperación, Conquest huyó de regreso con sus superiores para afrontar las consecuencias de su fracaso. Thragg le perdonó la vida, dándole una última oportunidad de redención al dar caza a los traidores: Nolan y su hijo, Invincible. En el apogeo de la Guerra Viltrumita , finalmente fue derrotado por Invincible en su batalla final , antes de recibir un entierro digno por parte de Nolan.';

String oniman =
    'Origen y la Gran Mentira Nolan llegó a la Tierra afirmando ser un alienígena de Viltrum, un planeta utópico y pacífico que enviaba protectores a mundos menos avanzados para ayudarlos a progresar. En la Tierra adoptó la identidad de Nolan Grayson, un exitoso escritor de novelas de viajes, se casó con una humana llamada Debbie y tuvo un hijo, Mark Grayson (quien más tarde se convierte en Invincible).La realidad es radicalmente opuesta: el Imperio Viltrumita es una raza de conquistadores fascistas. Su cultura se basa en la supervivencia del más fuerte (literalmente purgaron a la mitad de su propia población débil) y Nolan fue enviado a la Tierra no para protegerla, sino para debilitarla y prepararla para una futura anexión.';

String inivincible =
    'Markus Sebastian "Mark" Grayson es el protagonista principal de la serie Invincible . Híbrido viltrumita-humano, es el superhéroe conocido como Invincible, hijo de Nolan Grayson/Omni-Man y Debbie Grayson, hermanastro paterno mayor de Oliver Grayson y nieto materno de Oliver. También es el novio de Eve Wilkins/Atom Eve. A los 17 años, Mark obtuvo sus poderes y comenzó su aventura como superhéroe bajo la tutela de su padre. Tras un breve paso por el Equipo Juvenil, se unió a Atom Eve, confesándole finalmente sus sentimientos e iniciando una relación romántica duradera. También se unió a la segunda encarnación de los Guardianes del Globo y trabajó junto a Cecil Stedman y la Agencia de Defensa Global para proteger la Tierra de diversas amenazas.';
